[field] # Размеры поля
length = 8 # Длина, ось Y
width = 5 # Ширина, ось X

[direction_probabilities] # Вероятности направлений (в сумме должны давать 1!!!)
forward = 0.3 # Вперёд
backward = 0.1 # Назад
leftward = 0.15 # Влево
rightward = 0.15 # Вправо
upward = 0.15 # Вверх
downward = 0.15 # Вниз

# Для корректного отображения заголовки признаков рекомендуется писать с заглавной буквы,
# а сами признаки - с прописной

[useful_trait] # Полезный признак, который всегда присутствует у голов определённого типа
title = "Рога" # Название признака
truth = "прямые" # Признак головы правды
lies = "закрученные" # Признак головы лжи
repeat = "короткие" # Признак головы повтора

# Бесполезные признаки голов
# Их может быть сколько угодно, но важно, чтобы количество заголовков и наборов признаков совпадало
[useless_traits]

# Заголовки признаков
titles = ["Цвет шерсти", "Цвет глаз", "Бородка"]

# Наборы признаков
data = [
    ["коричневый", "белый", "серый", "чёрный"],
    ["жёлтый", "красный", "белый"],
    ["есть", "нет"]
]